language: java

addons:
  homebrew:
    update: true
    packages: ant

matrix:
  include:
    - jdk: openjdk7
    # - jdk: openjdk8
    - jdk: oraclejdk8
    # - jdk: oraclejdk9
    # - jdk: oraclejdk11  # times out
    - os: osx
      name: "JDK: oraclejdk10 Java on macOS"
      install: export JAVA_HOME=$(/usr/libexec/java_home)

addons:
  hostname: jyshort

before_install:
  - cat /etc/hosts # optionally check the content *after*

install: ant

script: ant && ant regrtest-travis

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net
